#!/bin/bash
Rscript ./binder/install.R
echo "Sys.setenv(RETICULATE_MINICONDA_ENABLED='FALSE')" >> /srv/conda/envs/notebook/lib/R/etc/Rprofile.site
jupyter serverextension enable --sys-prefix jupyter_server_proxy
